title: "<strong>Yu</strong> Zhang"
position: Researcher
affiliation: Moonshot AI
email: yzhang [dot] cs [at] outlook [dot] com
bio: "Hi, my name is Yu Zhang ([jy tʃɑŋ], 張宇/张宇 in traditional/simplified Chinese). I am a researcher at [Moonshot AI](https://www.moonshot.cn/). Prior to this, I received my Ph.D. degree from Soochow University in 2026, advised by [Prof. Guohong Fu](http://web.suda.edu.cn/ghfu/)."

plugins:
  - jekyll-spaceship
  - jekyll-analytics

keywords: minimal academic
description:
  AI Researcher @ [Moonshot AI](https://www.moonshot.cn/)
canonical: https://yzhang.site

semantic_scholar: https://www.semanticscholar.org/author/Yu-Zhang/49890808
google_scholar: https://scholar.google.com/citations?user=y3JK-1oAAAAJ
cv_link: ./assets/files/cv.pdf
github_link: https://github.com/yzhangcs
arxiv_link: ./arxiv

avatar: ./assets/img/avatar.png
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

jekyll_analytics:
  GoogleAnalytics:
    id: UA-249984993-1

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
